const $ = id => document.getElementById(id);
let password = "", data;
async function api(action, payload = {}) { const response = await fetch("/api/admin", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({action, adminPassword:password, ...payload}) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Erreur serveur"); return result; }
function message(text, error = false) { $("message").textContent = text; $("message").style.color = error ? "#a22" : "#275f38"; }
function classesOptions(selected = []) { return data.classCatalog.map(item => `<option value="${item.name}" ${selected.includes(item.name) ? "selected" : ""}>${item.name}</option>`).join(""); }
function render() { $("teachers").innerHTML = data.teachers.map(t => teacherRow(t)).join(""); $("classes").innerHTML = data.classCatalog.map(c => classRow(c)).join(""); $("student-class").innerHTML = classesOptions(); renderStudents(); $("questions").innerHTML = Object.entries(data.questionSets).map(([series, questions]) => `<h3>${series}</h3>${questions.map((q,i) => `<article class="question"><strong>${i+1}. ${q[0]}</strong><span>Durée : ${q[1]} s</span><span><b>Correction :</b> ${q[2] || "—"}</span>${q[3] ? `<img src="${q[3]}" alt="Figure de la question">` : ""}</article>`).join("")}`).join(""); }
function teacherRow(t = {teacher_id:"",name:"",classes:[]}) { return `<div class="row teacher-row"><label>Identifiant<input class="tid" value="${t.teacher_id || ""}"></label><label>Nom<input class="tname" value="${t.name || ""}"></label><label>Mot de passe<input class="tpass" type="password" placeholder="${t.teacher_id ? "laisser vide pour conserver" : "requis"}"></label><label>Classes<select class="tclasses" multiple>${classesOptions(t.classes || [])}</select></label><button class="save-teacher">Enregistrer</button>${t.teacher_id ? `<button class="delete-teacher danger">Supprimer</button>` : ""}</div>`; }
function classRow(c = {name:"",color:"#9766bc"}) { const progression=data.progression.find(p=>p.class_name===c.name)||{position:0,rounds:0}; return `<div class="row class-row"><label>Nom<input class="cname" value="${c.name}"></label><label>Couleur<input class="ccolor" type="color" value="${c.color}"></label><label>Position (0–223)<input class="cposition" type="number" min="0" max="223" value="${progression.position}"></label><label>Séries<input class="crounds" type="number" min="0" value="${progression.rounds}"></label><button class="save-class">Enregistrer</button>${c.name ? `<button class="save-progression">Mettre à jour le jeu</button><button class="delete-class danger">Supprimer</button>` : ""}</div>`; }
function renderStudents() { const name = $("student-class").value; const list = data.students[name] || []; $("students-text").value = list.join("\n"); $("student-count").textContent = `${list.length} élève${list.length>1?"s":""}`; }
function csvNames(text) { return text.replace(/^\uFEFF/, "").split(/\r?\n/).slice(1).map(line => { const match=line.match(/^\s*"([^"]+)"|^\s*([^;,]+)/); return (match?.[1] || match?.[2] || "").trim(); }).filter(Boolean); }
$("admin-login-form").addEventListener("submit", async e => { e.preventDefault(); password=$("admin-password").value; try { data=await api("admin-data"); $("admin-login").hidden=true; $("admin-app").hidden=false; render(); } catch(e) { message(e.message,true); } });
$("add-teacher").onclick=()=>$("teachers").insertAdjacentHTML("beforeend",teacherRow()); $("add-class").onclick=()=>$("classes").insertAdjacentHTML("beforeend",classRow());
document.addEventListener("click", async e => { const row=e.target.closest(".teacher-row"); try { if(e.target.matches(".save-teacher")){const teacher={id:row.querySelector(".tid").value,name:row.querySelector(".tname").value,password:row.querySelector(".tpass").value,classes:[...row.querySelector(".tclasses").selectedOptions].map(o=>o.value)};data=await api("admin-save-teacher",{teacher});render();message("Professeur enregistré.");} if(e.target.matches(".delete-teacher")){if(!confirm("Supprimer ce professeur ?"))return;data=await api("admin-delete-teacher",{teacherId:row.querySelector(".tid").value});render();message("Professeur supprimé.");} const crow=e.target.closest(".class-row");if(e.target.matches(".save-class")){data=await api("admin-save-class",{item:{name:crow.querySelector(".cname").value,color:crow.querySelector(".ccolor").value}});render();message("Classe enregistrée.");}if(e.target.matches(".save-progression")){data=await api("admin-save-progression",{className:crow.querySelector(".cname").value,position:Number(crow.querySelector(".cposition").value),rounds:Number(crow.querySelector(".crounds").value)});render();message("Progression mise à jour.");}if(e.target.matches(".delete-class")){if(!confirm("Supprimer cette classe et sa progression ?"))return;data=await api("admin-delete-class",{className:crow.querySelector(".cname").value});render();message("Classe supprimée.");}}catch(err){message(err.message,true)}});
$("student-class").onchange=renderStudents; $("import-csv").onclick=async()=>{try{const file=$("csv-file").files[0];if(!file)return message("Choisissez un fichier CSV.",true);const students=csvNames(await file.text());if(!students.length)return message("Aucun élève détecté dans ce fichier.",true);$("students-text").value=students.join("\n");data=await api("admin-save-students",{className:$("student-class").value,students});render();message(`${students.length} élèves importés et enregistrés.`);}catch(e){message(e.message,true)}}; $("save-students").onclick=async()=>{try{data=await api("admin-save-students",{className:$("student-class").value,students:$("students-text").value.split(/\r?\n/)});render();message("Élèves enregistrés.");}catch(e){message(e.message,true)}};
