const teachers = {
  garrel: { name: "Mme Garrel", password: "garrel2026", classes: ["6ème 1", "6ème 2"] },
  takhedmit: { name: "M. Takhedmit", password: "takhedmit2026", classes: ["6ème 2", "6ème 3"] },
  marovelli: { name: "Mme Marovelli", password: "marovelli2026", classes: ["6ème 3", "6ème 4"] },
  berquet: { name: "M. Berquet", password: "berquet2026", classes: ["6ème 4", "6ème 5"] }
};
const classNames = ["6ème 1", "6ème 2", "6ème 3", "6ème 4", "6ème 5"];
const classColors = ["#e15a4f", "#4e92ca", "#55a66f", "#e7a13b", "#9766bc"];
const students = {
  "6ème 1": ["Lucas", "Chloé", "Nathan", "Inès", "Thomas", "Manon"],
  "6ème 2": ["Louis", "Louise", "Jules", "Alice", "Adam", "Lina"],
  "6ème 3": ["Arthur", "Emma", "Noah", "Léa", "Sacha", "Zoé"],
  "6ème 4": ["Léonie", "Timéo", "Agathe", "Tom", "Louise", "Léon"],
  "6ème 5": ["Gabriel", "Sarah", "Hugo", "Jade", "Enzo", "Mila"]
};
const questionSets = {
  "Série 10": [["Combien de minutes représentent les trois quarts de 3 heures ?",45,"3 × 60 × 3/4 = 135 minutes."],["262 − ? = 87",45,"262 − 175 = 87."],["49 billes sont partagées entre 5 élèves. Combien en reste-t-il ?",60,"5 × 9 = 45 : il reste 4 billes."],["Quelle fraction de la figure est grisée ?",30,"La fraction correspond à 3/8."],["Calcule : (27 ÷ 9 + 18) × 2.",60,"27 ÷ 9 = 3 ; 3 + 18 = 21 ; 21 × 2 = 42."]],
  "Série 11": [["9 × 9 − 15 = ?",45,"81 − 15 = 66."],["3 jours et 9 heures = … heures",60,"3 × 24 + 9 = 81 heures."],["Triangle dont les trois côtés sont de même mesure ?",30,"Un triangle équilatéral."],["Combien de fois 7 dans 420 ?",60,"7 × 60 = 420 : il y a 60 fois 7."],["50 € moins la moitié de la moitié : combien reste-t-il ?",60,"La dépense est 12,50 €, il reste 37,50 €."]]
};
const labels = ["DÉPART","Euclide","Pythagore","Descartes","Galois","Fibonacci","Riemann","Al-Karaji","Thalès","Hypatie","Fermat","Leibniz","Pascal","Desargues","Gauss","Euler","Turing","Boole","Cantor","Lagrange","Poisson","Laplace","Fourier","Cardan","Archimède","Ératosthène","Diophante","Napier","Brahmagupta","Bhaskara","Aryabhata","Zu Chongzhi","Héron","Ménélaüs","Ptolémée","Apollonius","Eudoxe","Zénon","Hippias","Anaxagore","Platon","Aristote","Bachet","Roberval","Mersenne","Torricelli","Viviani","Cavalieri","Newton","Stokes","Green","Hamilton","Galilée","Copernic","Kepler","Poincaré","Hilbert","Noether","Kowalevskaia","Germain","Lovelace","Ramanujan","Cauchy","Lagrange","Palais des Mathématiques"];
const state = { teacher: null, current: 0, question: 0, series: "Série 10", timer: null, moving: false, correctAnswers: 0, classes: Object.fromEntries(classNames.map((name, i) => [name, { pos: 0, color: classColors[i] }])) };
const $ = id => document.getElementById(id); const svgNS = "http://www.w3.org/2000/svg";
function notify(text) { const toast = $("toast"); toast.textContent = text; toast.classList.add("visible"); clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.classList.remove("visible"), 3200); }
function isPrime(n) { if (n < 2) return false; for (let i = 2; i * i <= n; i++) if (n % i === 0) return false; return true; }
function spiralCoordinates() { const cells = [], add = (r, c) => cells.push({ x: 30 + c * 60, y: 30 + r * 60 }); let top = 0, bottom = 14, left = 0, right = 14; while (top <= bottom && left <= right) { for (let r = top; r <= bottom; r++) add(r, left); left++; for (let c = left; c <= right; c++) add(bottom, c); bottom--; for (let r = bottom; r >= top; r--) add(r, right); right--; for (let c = right; c >= left; c--) add(top, c); top++; } const center = cells.findIndex(p => p.x === 450 && p.y === 450); if (center >= 0) cells.splice(center, 1); return cells; }
const points = spiralCoordinates();
function svg(name, attrs = {}) { const node = document.createElementNS(svgNS, name); Object.entries(attrs).forEach(([k, v]) => node.setAttribute(k, v)); return node; }
function renderBoard() { const board = $("game-board"); board.setAttribute("viewBox", "0 0 900 900"); board.innerHTML = ""; board.appendChild(svg("rect", { x: 0, y: 0, width: 900, height: 900, rx: 22, fill: "#efd193" })); const path = points.map(p => `${p.x},${p.y}`).join(" "); board.appendChild(svg("polyline", { points: path, fill: "none", stroke: "#a86c36", "stroke-width": 51, "stroke-linecap": "round", "stroke-linejoin": "round", opacity: ".28" })); board.appendChild(svg("polyline", { points: path, fill: "none", stroke: "#fff0bd", "stroke-width": 43, "stroke-linecap": "round", "stroke-linejoin": "round" })); const finish = svg("g"); finish.appendChild(svg("circle", { cx: 450, cy: 450, r: 76, fill: "#fff8e8", stroke: "#9c612e", "stroke-width": 5 })); const ft = svg("text", { x: 450, y: 443, "text-anchor": "middle", fill: "#704026", "font-size": 18, "font-weight": 900 }); ft.textContent = "FIN"; finish.appendChild(ft); const ft2 = svg("text", { x: 450, y: 468, "text-anchor": "middle", fill: "#704026", "font-size": 13, "font-weight": 900 }); ft2.textContent = "PALAIS"; finish.appendChild(ft2); board.appendChild(finish);
  points.forEach((point, i) => { const group = svg("g", { class: `cell ${i === 0 ? "cell-start" : i === 223 ? "cell-finish" : isPrime(i) ? "cell-bonus" : "cell-normal"}` }); group.appendChild(svg("circle", { cx: point.x, cy: point.y, r: 25 })); const n = svg("text", { x: point.x, y: point.y - 2, "text-anchor": "middle", class: "cell-number" }); n.textContent = i === 0 ? "D" : i; group.appendChild(n); const l = svg("text", { x: point.x, y: point.y + 13, "text-anchor": "middle", class: "cell-label" }); l.textContent = isPrime(i) ? "★" : (labels[i % labels.length] || ""); group.appendChild(l); board.appendChild(group); }); classNames.forEach((name, i) => { const pawn = svg("g", { id: `pawn-${i}`, class: "pawn" }); pawn.appendChild(svg("circle", { cx: 0, cy: 0, r: 17, fill: classColors[i], stroke: "#fff", "stroke-width": 4 })); const t = svg("text", { x: 0, y: 6, "text-anchor": "middle", fill: "#fff", "font-size": 14, "font-weight": 900 }); t.textContent = i + 1; pawn.appendChild(t); board.appendChild(pawn); }); positionPawns(); renderClasses(); }
function positionPawns() { const grouped = {}; classNames.forEach((name, i) => { const pos = state.classes[name].pos; grouped[pos] = (grouped[pos] || 0) + 1; const slot = grouped[pos]; const angle = (slot - 1) * Math.PI / 3; const radius = slot > 1 ? 20 : 0; const p = points[Math.min(pos, 223)]; $("pawn-" + i)?.setAttribute("transform", `translate(${p.x + Math.cos(angle) * radius} ${p.y + Math.sin(angle) * radius})`); }); }
function renderClasses() { const owned = state.teacher?.classes || []; $("team-list").innerHTML = classNames.map((name, i) => { const data = state.classes[name]; const canMove = owned.includes(name); return `<div class="team-row"><span class="team-dot" style="background:${data.color}"></span><strong>${name}<br><small>Case ${data.pos}${isPrime(data.pos) ? " · bonus +3" : ""}</small></strong>${canMove ? `<button data-class="${name}" data-step="-1">−</button><button data-class="${name}" data-step="1">+</button>` : `<small class="view-only">lecture seule</small>`}</div>`; }).join(""); const currentName = classNames[state.current]; $("current-team").textContent = currentName; $("turn-badge").textContent = `Tour de ${currentName}`; $("stage-team").textContent = currentName; $("teacher-session").textContent = `${state.teacher.name} · classes : ${state.teacher.classes.join(", ")}`; }
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
async function moveClass(name, steps) { if (state.moving || !state.teacher.classes.includes(name)) return; state.moving = true; const data = state.classes[name]; const direction = Math.sign(steps); for (let i = 0; i < Math.abs(steps); i++) { data.pos = Math.max(0, Math.min(223, data.pos + direction)); positionPawns(); await sleep(120); } if (steps > 0 && isPrime(data.pos)) { data.pos = Math.min(223, data.pos + 3); notify(`${name} tombe sur une case première : bonus de 3 cases !`); } renderClasses(); state.moving = false; }
function applyAnswer(correct) { const name = classNames[state.current]; let delta = correct ? 2 : -1; if (correct) state.correctAnswers++; else state.correctAnswers = 0; if (state.correctAnswers >= 5) { delta += 2; state.correctAnswers = 0; notify("Série de 5 bonnes réponses : bonus de 2 cases !"); } moveClass(name, delta); $("question-modal").classList.add("is-hidden"); state.current = (state.current + 1) % classNames.length; renderClasses(); }
function updateQuestion() { const q = questionSets[state.series][state.question]; $("stage-counter").textContent = `Question ${state.question + 1} / ${questionSets[state.series].length}`; $("stage-question").textContent = q[0]; $("correction-text").textContent = q[2]; $("timer-value").textContent = q[1]; $("timer-ring").style.setProperty("--progress", "100%"); $("timer-ring").classList.remove("urgent"); $("stage-correction").classList.add("is-hidden"); clearInterval(state.timer); }
function openQuestion() { updateQuestion(); $("question-modal").classList.remove("is-hidden"); }
function startTimer() { clearInterval(state.timer); const seconds = questionSets[state.series][state.question][1]; let left = seconds; state.timer = setInterval(() => { left--; $("timer-value").textContent = Math.max(0, left); $("timer-ring").style.setProperty("--progress", `${Math.max(0, left / seconds * 100)}%`); if (left <= 10) $("timer-ring").classList.add("urgent"); if (left <= 0) { clearInterval(state.timer); notify("Temps écoulé !"); } }, 1000); }
function drawStudent() { const list = students[$("class-select").value]; let count = 0; clearInterval(drawStudent.timer); drawStudent.timer = setInterval(() => { $("student-result").textContent = `🎲 ${list[Math.floor(Math.random() * list.length)]}`; if (++count > 12) { clearInterval(drawStudent.timer); const chosen = list[Math.floor(Math.random() * list.length)]; $("student-result").textContent = `🎯 ${chosen}`; notify(`${chosen} est désigné(e) !`); } }, 90); }
function login() { const teacher = teachers[$("teacher-select").value]; if (!teacher || $("password").value !== teacher.password) { notify("Identifiants incorrects"); $("password").value = ""; return; } state.teacher = teacher; $("login-screen").classList.add("is-hidden"); $("game-screen").classList.remove("is-hidden"); drawBoard(); updateQuestion(); }
$("login-form").addEventListener("submit", e => { e.preventDefault(); login(); }); $("logout").addEventListener("click", () => { $("game-screen").classList.add("is-hidden"); $("login-screen").classList.remove("is-hidden"); }); $("question-open").addEventListener("click", openQuestion); $("question-open-2").addEventListener("click", openQuestion); $("question-close").addEventListener("click", () => $("question-modal").classList.add("is-hidden")); $("timer-start").addEventListener("click", startTimer); $("show-correction").addEventListener("click", () => $("stage-correction").classList.toggle("is-hidden")); $("correct-answer").addEventListener("click", () => applyAnswer(true)); $("wrong-answer").addEventListener("click", () => applyAnswer(false)); $("next-question").addEventListener("click", () => { state.question = (state.question + 1) % questionSets[state.series].length; updateQuestion(); }); $("draw-student").addEventListener("click", drawStudent); $("team-list").addEventListener("click", e => { const button = e.target.closest("button[data-class]"); if (button) moveClass(button.dataset.class, Number(button.dataset.step)); });
$("roll-dice").addEventListener("click", openQuestion); $("login-form").addEventListener("submit", e => { e.preventDefault(); login(); }); $("logout").addEventListener("click", () => { $("game-screen").classList.add("is-hidden"); $("login-screen").classList.remove("is-hidden"); }); $("question-open").addEventListener("click", openQuestion); $("question-open-2").addEventListener("click", openQuestion); $("question-close").addEventListener("click", () => $("question-modal").classList.add("is-hidden")); $("timer-start").addEventListener("click", startTimer); $("show-correction").addEventListener("click", () => $("stage-correction").classList.toggle("is-hidden")); $("correct-answer").addEventListener("click", () => applyAnswer(true)); $("wrong-answer").addEventListener("click", () => applyAnswer(false)); $("next-question").addEventListener("click", () => { state.question = (state.question + 1) % questionSets[state.series].length; updateQuestion(); }); $("draw-student").addEventListener("click", drawStudent); $("team-list").addEventListener("click", e => { const button = e.target.closest("button[data-class]"); if (button) moveClass(button.dataset.class, Number(button.dataset.step)); });
