const PASSWORD = "maths2026";

const questionSets = {
  "Série 1": [
    ["9 × 8 = ?", 30, "9 × 8 = 72."], ["15 000 ÷ 100 = ?", 45, "15 000 ÷ 100 = 150."], ["729 − 177 = ?", 60, "729 − 177 = 552."], ["2 min 29 s = … s", 45, "2 × 60 + 29 = 149 secondes."], ["10 km = … m", 45, "10 km = 10 000 m."]
  ],
  "Série 10": [
    ["Combien de minutes représentent les trois quarts de 3 heures ?", 45, "3 × 60 × 3/4 = 135 minutes, soit 2 h 15."], ["262 − ? = 87", 45, "262 − 175 = 87."], ["49 billes sont partagées entre 5 élèves. Combien en reste-t-il ?", 60, "5 × 9 = 45 : il reste 4 billes."], ["Quelle fraction de la figure est grisée ?", 30, "La fraction correspond à 3/8."], ["Calcule : (27 ÷ 9 + 18) × 2.", 60, "27 ÷ 9 = 3 ; 3 + 18 = 21 ; 21 × 2 = 42."]
  ],
  "Série 11": [
    ["9 × 9 − 15 = ?", 45, "81 − 15 = 66."], ["3 jours et 9 heures = … heures", 60, "3 × 24 + 9 = 81 heures."], ["Triangle dont les trois côtés sont de même mesure ?", 30, "Un triangle équilatéral."], ["Combien de fois 7 dans 420 ?", 60, "7 × 60 = 420 : il y a 60 fois 7."], ["50 € moins la moitié de la moitié : combien reste-t-il ?", 60, "La dépense est 12,50 €, il reste 37,50 €."]
  ]
};
const students = { "6ème A": ["Lucas", "Chloé", "Nathan", "Inès", "Thomas", "Manon", "Gabriel", "Sarah"], "6ème B": ["Louis", "Louise", "Jules", "Alice", "Adam", "Lina", "Enzo", "Mila"], "6ème C": ["Arthur", "Emma", "Noah", "Léa", "Sacha", "Zoé", "Ethan", "Chloé"], "6ème D": ["Léonie", "Timéo", "Agathe", "Tom", "Louise", "Léon", "Camille", "Paul"] };
const labels = ["DÉPART • Al-Khawarizmi", "Euclide • nombres premiers", "Pythagore • théorème", "Descartes • repère", "Galois • groupes", "PONT • va en 12", "Riemann • géométrie", "Fibonacci • suite", "Al-Karaji • algèbre", "Thalès • proportion", "Hypatie • astronomie", "Fibonacci • suite", "Fermat • nombres", "Leibniz • calcul", "Pascal • triangle", "Desargues • perspective", "Gauss • somme", "Euler • graphe", "HÔTEL • pause", "Turing • logique", "Boole • logique", "Cantor • infini", "Lagrange • fonctions", "Poisson • probabilités", "Laplace • hasard", "Fourier • signaux", "Cardan • équations", "Archimède • aire", "Ératosthène • crible", "Diophante • équations", "PUITS • retour 30", "Napier • logarithmes", "Brahmagupta • zéro", "Bhaskara • équations", "Aryabhata • calcul", "Zu Chongzhi • π", "Héron • aire", "Ménélaüs • géométrie", "Ptolémée • cercle", "Apollonius • coniques", "Eudoxe • proportions", "LABYRINTHE • retour 30", "Zénon • paradoxe", "Hippias • courbes", "Anaxagore • figures", "Platon • solides", "Aristote • logique", "PRISON • passe un tour", "Bachet • récréations", "Roberval • tangentes", "Mersenne • nombres", "Torricelli • volume", "Viviani • théorème", "TÊTE DE MORT • retour 0", "Cavalieri • indivisibles", "Newton • calcul", "Stokes • flux", "Green • champ", "Hamilton • chemins", "Galilée • mesure", "Copernic • modèle", "Kepler • orbites", "Poincaré • topologie", "Hilbert • problèmes", "Noether • symétries", "Kowalevskaia • analyse", "Germain • théorie", "Lovelace • algorithme", "Ramanujan • séries", "Cauchy • limites", "Lagrange • mécanique", "PALAIS DES MATHÉMATIQUES"];
const colors = ["#e15a4f", "#4e92ca", "#55a66f", "#e7a13b", "#9766bc", "#d56898"];
const state = { teams: Array.from({ length: 6 }, (_, i) => ({ name: `Équipe ${i + 1}`, pos: 0 })), current: 0, series: "Série 10", question: 0, timer: null, moving: false };
const $ = id => document.getElementById(id);
const svgNS = "http://www.w3.org/2000/svg";

function notify(text) { const toast = $("toast"); toast.textContent = text; toast.classList.add("visible"); clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.classList.remove("visible"), 3000); }
function coords() { const a = [], add = (r, c) => a.push({ x: 55 + c * 100, y: 55 + r * 72 }); for (let c = 0; c < 9; c++) add(0, c); for (let r = 1; r < 9; r++) add(r, 8); for (let c = 7; c >= 0; c--) add(8, c); for (let r = 7; r >= 1; r--) add(r, 0); for (let c = 1; c < 8; c++) add(1, c); for (let r = 2; r < 8; r++) add(r, 7); for (let c = 6; c >= 1; c--) add(7, c); for (let r = 6; r >= 2; r--) add(r, 1); for (let c = 2; c < 7; c++) add(2, c); for (let r = 3; r < 7; r++) add(r, 6); for (let c = 5; c >= 2; c--) add(6, c); for (let r = 5; r >= 3; r--) add(r, 2); for (let c = 3; c < 6; c++) add(3, c); add(4, 5); add(5, 5); return a; }
const points = coords();
function el(name, attrs = {}) { const node = document.createElementNS(svgNS, name); Object.entries(attrs).forEach(([key, value]) => node.setAttribute(key, value)); return node; }
function cellClass(i) { if (i === 0) return "start"; if (i === 71) return "finish"; if ([30, 41, 53].includes(i)) return "trap"; if ([5, 18, 47].includes(i)) return "special"; return i % 4 === 0 ? "warm" : "normal"; }
function drawBoard() {
  const board = $("game-board"); board.innerHTML = "";
  board.appendChild(el("rect", { x: 0, y: 0, width: 900, height: 760, rx: 24, fill: "#efd193" }));
  const path = points.map(p => `${p.x},${p.y}`).join(" "); board.appendChild(el("polyline", { points: path, fill: "none", stroke: "#a86c36", "stroke-width": 40, "stroke-linecap": "round", "stroke-linejoin": "round", opacity: ".28" })); board.appendChild(el("polyline", { points: path, fill: "none", stroke: "#fff0bd", "stroke-width": 32, "stroke-linecap": "round", "stroke-linejoin": "round" }));
  const center = el("g"); center.appendChild(el("circle", { cx: 455, cy: 350, r: 112, fill: "#fff8e8", stroke: "#9c612e", "stroke-width": 4 })); const title = el("text", { x: 455, y: 340, "text-anchor": "middle", fill: "#704026", "font-size": 22, "font-weight": 900 }); title.textContent = "PALAIS DES"; center.appendChild(title); const title2 = el("text", { x: 455, y: 369, "text-anchor": "middle", fill: "#704026", "font-size": 22, "font-weight": 900 }); title2.textContent = "MATHÉMATIQUES"; center.appendChild(title2); board.appendChild(center);
  points.forEach((point, i) => { const group = el("g", { class: `cell cell-${cellClass(i)}` }); group.appendChild(el("circle", { cx: point.x, cy: point.y, r: 20 })); const number = el("text", { x: point.x, y: point.y - 4, "text-anchor": "middle", class: "cell-number" }); number.textContent = i === 0 ? "D" : i; group.appendChild(number); const label = el("text", { x: point.x, y: point.y + 9, "text-anchor": "middle", class: "cell-label" }); label.textContent = i === 0 ? "DÉPART" : i === 71 ? "ARRIVÉE" : labels[i].split(" • ")[0]; group.appendChild(label); board.appendChild(group); });
  state.teams.forEach((team, i) => { const pawn = el("g", { class: "pawn", id: `pawn-${i}` }); pawn.appendChild(el("circle", { cx: 0, cy: 0, r: 13, fill: colors[i], stroke: "#fff", "stroke-width": 3 })); const text = el("text", { x: 0, y: 5, "text-anchor": "middle", fill: "#fff", "font-size": 12, "font-weight": 900 }); text.textContent = i + 1; pawn.appendChild(text); board.appendChild(pawn); }); positionPawns(); renderTeams(); }
function positionPawns() { const offsets = {}; state.teams.forEach((team, i) => { const key = team.pos; offsets[key] = (offsets[key] || 0) + 1; const slot = offsets[key]; const angle = (slot - 1) * Math.PI / 3; const radius = slot > 1 ? 10 : 0; const x = points[team.pos].x + Math.cos(angle) * radius; const y = points[team.pos].y + Math.sin(angle) * radius; $("pawn-" + i)?.setAttribute("transform", `translate(${x} ${y})`); }); }
function renderTeams() { $("team-list").innerHTML = state.teams.map((team, i) => `<div class="team-row"><span class="team-dot team-${i + 1}"></span><strong>${team.name}<br><small>Case ${team.pos}</small></strong><button data-team="${i}" data-step="-1">−</button><button data-team="${i}" data-step="1">+</button></div>`).join(""); $("current-team").textContent = state.teams[state.current].name; $("turn-badge").textContent = `Tour de ${state.teams[state.current].name}`; $("stage-team").textContent = state.teams[state.current].name; }
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
async function moveTeam(index, steps) { if (state.moving) return; state.moving = true; const team = state.teams[index]; for (let n = 0; n < steps; n++) { if (team.pos >= 71) break; team.pos++; positionPawns(); await sleep(280); } if (team.pos === 5) { team.pos = 12; notify(`${team.name} franchit le Pont !`); } else if (team.pos === 30) notify(`${team.name} tombe dans le Puits !`); else if (team.pos === 41) { team.pos = 30; notify(`${team.name} se perd dans le Labyrinthe !`); } else if (team.pos === 53) { team.pos = 0; notify(`${team.name} retourne au départ !`); } renderTeams(); state.moving = false; if (team.pos === 71) notify(`🏆 ${team.name} atteint le Palais !`); }
function rollDice() { if (state.moving) return; const dice = $("dice"); dice.classList.add("rolling"); let count = 0; const spin = setInterval(() => { dice.textContent = 1 + Math.floor(Math.random() * 6); count++; if (count > 7) { clearInterval(spin); dice.classList.remove("rolling"); const value = Number(dice.textContent); const team = state.teams[state.current]; $("move-message").textContent = `${team.name} avance de ${value} case${value > 1 ? "s" : ""} !`; moveTeam(state.current, value).then(() => { state.current = (state.current + 1) % state.teams.length; renderTeams(); }); } }, 80); }
function updateQuestion() { const q = questionSets[state.series][state.question]; $("stage-counter").textContent = `Question ${state.question + 1} / ${questionSets[state.series].length}`; $("stage-question").textContent = q[0]; $("correction-text").textContent = q[2]; $("timer-value").textContent = q[1]; $("timer-ring").style.setProperty("--progress", "100%"); $("timer-ring").classList.remove("urgent"); $("stage-correction").classList.add("is-hidden"); $("timer-label").textContent = "À toi de réfléchir !"; $("mini-question").textContent = q[0]; clearInterval(state.timer); }
function openQuestion() { updateQuestion(); $("question-modal").classList.remove("is-hidden"); }
function startTimer() { clearInterval(state.timer); const seconds = questionSets[state.series][state.question][1]; let left = seconds; $("timer-value").textContent = left; $("timer-label").textContent = "Le temps défile…"; state.timer = setInterval(() => { left--; $("timer-value").textContent = Math.max(0, left); $("timer-ring").style.setProperty("--progress", `${Math.max(0, left / seconds * 100)}%`); if (left <= 10) $("timer-ring").classList.add("urgent"); if (left <= 0) { clearInterval(state.timer); $("timer-label").textContent = "Temps écoulé !"; notify("⏰ Temps écoulé !"); } }, 1000); }
function drawStudent() { const list = students[$("class-select").value]; let count = 0; clearInterval(drawStudent.timer); drawStudent.timer = setInterval(() => { $("student-result").textContent = `🎲 ${list[Math.floor(Math.random() * list.length)]}`; if (++count > 12) { clearInterval(drawStudent.timer); const chosen = list[Math.floor(Math.random() * list.length)]; $("student-result").textContent = `🎯 ${chosen}`; notify(`${chosen} est désigné(e) !`); } }, 90); }
function login() { if ($("password").value !== PASSWORD) { notify("Mot de passe incorrect"); $("password").value = ""; return; } $("login-screen").classList.add("is-hidden"); $("game-screen").classList.remove("is-hidden"); drawBoard(); updateQuestion(); }
$("login-form").addEventListener("submit", e => { e.preventDefault(); login(); }); $("logout").addEventListener("click", () => { $("game-screen").classList.add("is-hidden"); $("login-screen").classList.remove("is-hidden"); }); $("roll-dice").addEventListener("click", rollDice); $("question-open").addEventListener("click", openQuestion); $("question-open-2").addEventListener("click", openQuestion); $("question-close").addEventListener("click", () => $("question-modal").classList.add("is-hidden")); $("timer-start").addEventListener("click", startTimer); $("show-correction").addEventListener("click", () => $("stage-correction").classList.toggle("is-hidden")); $("next-question").addEventListener("click", () => { state.question = (state.question + 1) % questionSets[state.series].length; updateQuestion(); }); $("draw-student").addEventListener("click", drawStudent); $("team-list").addEventListener("click", e => { const button = e.target.closest("button[data-team]"); if (button) moveTeam(Number(button.dataset.team), Number(button.dataset.step)); });
