const teachers = {
  garrel: { name: "Mme Garrel", password: "garrel2026", classes: ["6ème 1", "6ème 2"] },
  takhedmit: { name: "M. Takhedmit", password: "takhedmit2026", classes: ["6ème 2", "6ème 3"] },
  marovelli: { name: "Mme Marovelli", password: "marovelli2026", classes: ["6ème 3", "6ème 4"] },
  berquet: { name: "M. Berquet", password: "berquet2026", classes: ["6ème 4", "6ème 5"] }
};
const classNames = ["6ème 1", "6ème 2", "6ème 3", "6ème 4", "6ème 5"];
const classColors = ["#e15a4f", "#4e92ca", "#55a66f", "#e7a13b", "#9766bc"];
const students = {
  "6ème 1": ["Lucas", "Chloé", "Nathan", "Inès", "Thomas", "Manon"],
  "6ème 2": ["Louis", "Louise", "Jules", "Alice", "Adam", "Lina"],
  "6ème 3": ["Arthur", "Emma", "Noah", "Léa", "Sacha", "Zoé"],
  "6ème 4": ["Léonie", "Timéo", "Agathe", "Tom", "Louise", "Léon"],
  "6ème 5": ["Gabriel", "Sarah", "Hugo", "Jade", "Enzo", "Mila"]
};
const questionSets = {
  "Série 1": [["9 × 8 = ?",30,"9 × 8 = 72."],["15 000 ÷ 100 = ?",45,"15 000 ÷ 100 = 150."],["729 − 177 = ?",60,"729 − 177 = 552."],["2 min 29 s = … s",45,"2 min = 120 s ; 120 + 29 = 149 s."],["10 km = … m",45,"10 km = 10 000 m."]],
  "Série 2": [["247 − 139 = ?",45,"247 − 139 = 108."],["4 h 38 min = … min",60,"4 × 60 min + 38 min = 278 min."],["Quel est le rang du chiffre 7 dans 23 478 905 ?",30,"7 est le chiffre des dizaines de milliers."],["8 dag = … mg",45,"8 dag = 80 000 mg."],["Combien y a-t-il de centaines de milliers dans 4 367 987 ?",45,"Le nombre possède 43 centaines de milliers."]],
  "Série 3": [["15 × 8 = ?",45,"15 × 8 = 120."],["Combien y a-t-il d’unités de milliers dans 4 367 987 ?",45,"Le nombre possède 4 367 unités de milliers."],["12 min 5 s = … secondes",60,"12 × 60 + 5 = 725 secondes."],["Quel est le rang du chiffre 3 dans 23 478 905 ?",30,"3 est le chiffre des unités de millions."],["De 13 h 15 à 13 h 51, combien de temps dure le trajet ?",45,"Le trajet dure 36 minutes."]],
  "Série 4": [["17 × 9 = ?",45,"17 × 9 = 153."],["12 roses coûtent 30 €. Combien coûtent 18 roses ?",45,"18 roses coûtent 45 €."],["Combien y a-t-il d’heures dans 3 jours et 13 heures ?",60,"3 × 24 h + 13 h = 85 h."],["31 cg = … g",45,"31 cg = 0,31 g."],["De 13 h 07 à 13 h 55, combien de temps dure le trajet ?",60,"Le trajet dure 48 minutes."]],
  "Série 5": [["Quelle est la moitié de 126 ?",30,"La moitié de 126 est 63."],["5 glaces coûtent 15 €. Combien coûte une glace ?",45,"Une glace coûte 3 €."],["Calcule : 135 × 100.",30,"135 × 100 = 13 500.","pack-1/figures/serie-05-question-3-1.png"],["Combien y a-t-il de secondes dans 4 minutes et 33 secondes ?",60,"4 × 60 + 33 = 273 secondes."],["Quelle fraction du carré est représentée par la partie grisée ?",45,"La partie grisée représente 3/8.","pack-1/figures/serie-05-question-5-1.png"]],
  "Série 6": [["61,4 cm = … m",30,"61,4 cm = 0,614 m."],["De 13 h 21 à 14 h 09, combien de temps dure le trajet ?",60,"Le trajet dure 48 minutes."],["9 × 7 − 25 = ?",45,"9 × 7 − 25 = 38."],["Combien y a-t-il d’heures dans 3 jours et 7 heures ?",45,"3 × 24 h + 7 h = 79 h."],["Quelle fraction du carré est coloriée ?",45,"La partie coloriée représente 3/4.","pack-1/figures/serie-06-question-5-1.png"]],
  "Série 7": [["À quelle fraction de u correspond la partie grisée ?",45,"La partie grisée correspond à 3/4.","pack-1/figures/serie-07-question-1-1.png"],["Inès a 12 cartes. Elle en a 4 fois plus que Léo. Combien Léo a-t-il de cartes ?",45,"Léo possède 3 cartes."],["11 × 9 − 31 = ?",45,"11 × 9 − 31 = 68."],["0,5 L = … mL",45,"0,5 L = 500 mL."],["Prends 23, multiplie-le par 3, soustrais 27 puis ajoute son chiffre des unités.",60,"23 × 3 = 69 ; 69 − 27 = 42 ; 42 + 3 = 45."]],
  "Série 8": [["Yacine mesure 1,52 m. Il mesure 13 cm de plus que Pierre. Quelle est la taille de Pierre ?",45,"1,52 − 0,13 = 1,39 m."],["12 pains au chocolat coûtent 15 €. Combien coûtent 18 pains au chocolat ?",60,"15 € + 7,50 € = 22,50 €."],["Un train part à 10 h 49. Le trajet dure 1 h 13. À quelle heure arrive-t-il ?",45,"Le train arrive à 12 h 02."],["100 − ? = 71",45,"100 − 29 = 71."],["Prends 14, multiplie-le par 4, soustrais 19 puis ajoute le double de son chiffre des unités.",60,"14 × 4 = 56 ; 56 − 19 = 37 ; 37 + 8 = 45."]],
  "Série 9": [["Combien de minutes représentent le quart de 2 heures ?",45,"Le quart de 2 heures représente 30 minutes."],["En observant la succession de figures, combien de carrés composent le motif n°5 ?",60,"Le motif n°5 est composé de 21 carrés.","pack-1/figures/serie-09-question-2-1.png"],["3 élèves se partagent 35 billes équitablement. Combien en auront-ils chacun ?",60,"Ils auront 11 billes chacun et il en restera 2."],["De 13 h 41 à 15 h 17, quelle est la durée du trajet ?",45,"La durée du trajet est de 1 h 36."],["Prends 11, multiplie-le par 7, soustrais 18 puis ajoute le double de son chiffre des unités.",60,"11 × 7 = 77 ; 77 − 18 = 59 ; 59 + 2 = 61."]],
  "Série 10": [["Combien de minutes représentent les trois quarts de 3 heures ?",45,"3 × 60 × 3/4 = 135 minutes."],["262 − ? = 87",45,"262 − 175 = 87."],["5 élèves se partagent 49 billes équitablement. Combien en restera-t-il ?",60,"Ils auront 9 billes chacun et il en restera 4."],["Quelle fraction de la figure est grisée ?",30,"La fraction correspond à 3/8.","pack-1/figures/serie-10-question-4-1.png"],["Prends 27, divise-le par 9, ajoute 18 puis multiplie par le chiffre des dizaines de départ.",60,"27 ÷ 9 = 3 ; 3 + 18 = 21 ; 21 × 2 = 42."]],
  "Série 11": [["9 × 9 − 15 = ?",45,"81 − 15 = 66."],["3 jours et 9 heures = … heures",60,"3 × 24 + 9 = 81 heures."],["Je suis un triangle dont les trois côtés sont de même mesure. Qui suis-je ?",30,"Un triangle équilatéral."],["Combien de fois y a-t-il le nombre 7 dans 420 ?",60,"7 × 60 = 420 : il y a 60 fois 7."],["Avec 50 €, je dépense la moitié de la moitié. Combien me reste-t-il ?",60,"50 − 12,50 = 37,50 €."]]
};
const labels = ["DÉPART","Euclide","Pythagore","Descartes","Galois","Fibonacci","Riemann","Al-Karaji","Thalès","Hypatie","Fermat","Leibniz","Pascal","Desargues","Gauss","Euler","Turing","Boole","Cantor","Lagrange","Poisson","Laplace","Fourier","Cardan","Archimède","Ératosthène","Diophante","Napier","Brahmagupta","Bhaskara","Aryabhata","Zu Chongzhi","Héron","Ménélaüs","Ptolémée","Apollonius","Eudoxe","Zénon","Hippias","Anaxagore","Platon","Aristote","Bachet","Roberval","Mersenne","Torricelli","Viviani","Cavalieri","Newton","Stokes","Green","Hamilton","Galilée","Copernic","Kepler","Poincaré","Hilbert","Noether","Kowalevskaia","Germain","Lovelace","Ramanujan","Cauchy","Lagrange","Palais des Mathématiques"];
const state = { teacher: null, activeClass: null, current: 0, question: 0, series: "Série 10", timer: null, moving: false, challengeActive: false, correctAnswers: 0, classes: Object.fromEntries(classNames.map((name, i) => [name, { pos: 0, rounds: 0, color: classColors[i] }])) };
const $ = id => document.getElementById(id); const svgNS = "http://www.w3.org/2000/svg";
function notify(text) { const toast = $("toast"); toast.textContent = text; toast.classList.add("visible"); clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.classList.remove("visible"), 3200); }
function isPrime(n) { if (n < 2) return false; for (let i = 2; i * i <= n; i++) if (n % i === 0) return false; return true; }
function spiralCoordinates() { const cells = [], add = (r, c) => cells.push({ x: 30 + c * 60, y: 30 + r * 60 }); let top = 0, bottom = 14, left = 0, right = 14; while (top <= bottom && left <= right) { for (let r = top; r <= bottom; r++) add(r, left); left++; for (let c = left; c <= right; c++) add(bottom, c); bottom--; for (let r = bottom; r >= top; r--) add(r, right); right--; for (let c = right; c >= left; c--) add(top, c); top++; } const center = cells.findIndex(p => p.x === 450 && p.y === 450); if (center >= 0) cells.splice(center, 1); return cells; }
const points = spiralCoordinates();
function svg(name, attrs = {}) { const node = document.createElementNS(svgNS, name); Object.entries(attrs).forEach(([k, v]) => node.setAttribute(k, v)); return node; }
function renderBoard() { const board = $("game-board"); board.setAttribute("viewBox", "0 0 900 900"); board.innerHTML = ""; board.appendChild(svg("rect", { x: 0, y: 0, width: 900, height: 900, rx: 22, fill: "#efd193" })); const path = points.map(p => `${p.x},${p.y}`).join(" "); board.appendChild(svg("polyline", { points: path, fill: "none", stroke: "#a86c36", "stroke-width": 51, "stroke-linecap": "round", "stroke-linejoin": "round", opacity: ".28" })); board.appendChild(svg("polyline", { points: path, fill: "none", stroke: "#fff0bd", "stroke-width": 43, "stroke-linecap": "round", "stroke-linejoin": "round" })); const finish = svg("g"); finish.appendChild(svg("circle", { cx: 450, cy: 450, r: 76, fill: "#fff8e8", stroke: "#9c612e", "stroke-width": 5 })); const ft = svg("text", { x: 450, y: 443, "text-anchor": "middle", fill: "#704026", "font-size": 18, "font-weight": 900 }); ft.textContent = "FIN"; finish.appendChild(ft); const ft2 = svg("text", { x: 450, y: 468, "text-anchor": "middle", fill: "#704026", "font-size": 13, "font-weight": 900 }); ft2.textContent = "PALAIS"; finish.appendChild(ft2); board.appendChild(finish);
  points.forEach((point, i) => { const group = svg("g", { class: `cell ${i === 0 ? "cell-start" : i === 223 ? "cell-finish" : isPrime(i) ? "cell-bonus" : "cell-normal"}` }); group.appendChild(svg("circle", { cx: point.x, cy: point.y, r: 25 })); const n = svg("text", { x: point.x, y: point.y - 2, "text-anchor": "middle", class: "cell-number" }); n.textContent = i === 0 ? "D" : i; group.appendChild(n); const l = svg("text", { x: point.x, y: point.y + 13, "text-anchor": "middle", class: "cell-label" }); l.textContent = isPrime(i) ? "★" : (labels[i % labels.length] || ""); group.appendChild(l); board.appendChild(group); }); classNames.forEach((name, i) => { const pawn = svg("g", { id: `pawn-${i}`, class: "pawn" }); pawn.appendChild(svg("circle", { cx: 0, cy: 3, r: 19, fill: "#704026", opacity: ".28" })); pawn.appendChild(svg("circle", { cx: 0, cy: 0, r: 17, fill: classColors[i], stroke: "#fff", "stroke-width": 4 })); pawn.appendChild(svg("circle", { cx: -6, cy: -7, r: 4, fill: "#fff", opacity: ".7" })); board.appendChild(pawn); }); positionPawns(); renderClasses(); }
function pawnPosition(name, slotByPosition) { const classIndex = classNames.indexOf(name); const pos = state.classes[name].pos; const slot = slotByPosition[pos] || 1; const angle = (slot - 1) * Math.PI / 3; const radius = slot > 1 ? 20 : 0; const point = points[Math.min(pos, 223)]; return { classIndex, x: point.x + Math.cos(angle) * radius, y: point.y + Math.sin(angle) * radius }; }
function positionPawns() { const grouped = {}; classNames.forEach(name => { const pos = state.classes[name].pos; grouped[pos] = (grouped[pos] || 0) + 1; }); const seen = {}; classNames.forEach(name => { const pos = state.classes[name].pos; seen[pos] = (seen[pos] || 0) + 1; const target = pawnPosition(name, seen); const pawn = $("pawn-" + target.classIndex); if (pawn) pawn.setAttribute("transform", `translate(${target.x} ${target.y})`); }); }
function animatePawn(name, fromPos) { const slotByPosition = {}; classNames.forEach(className => { const pos = className === name ? fromPos : state.classes[className].pos; slotByPosition[pos] = (slotByPosition[pos] || 0) + 1; }); const classIndex = classNames.indexOf(name); const pawn = $("pawn-" + classIndex); if (!pawn) return; const from = points[Math.min(fromPos, 223)]; const to = points[Math.min(state.classes[name].pos, 223)]; const start = performance.now(); const duration = 430; const frame = now => { const progress = Math.min(1, (now - start) / duration); const eased = progress < .5 ? 2 * progress * progress : 1 - Math.pow(-2 * progress + 2, 2) / 2; const hop = Math.sin(progress * Math.PI) * 22; pawn.setAttribute("transform", `translate(${from.x + (to.x - from.x) * eased} ${from.y + (to.y - from.y) * eased - hop})`); if (progress < 1) requestAnimationFrame(frame); else positionPawns(); }; requestAnimationFrame(frame); }
function renderClasses() { $("team-list").innerHTML = classNames.map((name) => { const data = state.classes[name]; return `<div class="team-row ${name === state.activeClass ? "active-team" : ""}"><span class="team-dot" style="background:${data.color}"></span><strong class="class-name">${name}</strong><span class="class-stats">Case ${data.pos}<br>${data.rounds} tour${data.rounds === 1 ? "" : "s"}${isPrime(data.pos) ? "<br>★ première" : ""}</span></div>`; }).join(""); const currentName = state.teacher?.classes[state.current] || ""; $("current-team").textContent = currentName; $("stage-team").textContent = currentName; $("teacher-session").textContent = `${state.teacher.name} · classe active : ${state.activeClass}`; }
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
async function moveClass(name, steps) { if (state.moving || !state.teacher.classes.includes(name)) return; state.moving = true; const data = state.classes[name]; const direction = Math.sign(steps); for (let i = 0; i < Math.abs(steps); i++) { const previous = data.pos; data.pos = Math.max(0, Math.min(223, data.pos + direction)); animatePawn(name, previous); await sleep(470); } renderClasses(); state.moving = false; }
async function applyAnswer(correct) { if (state.moving || !state.challengeActive) return; state.challengeActive = false; clearInterval(state.timer); $("correct-answer").disabled = true; $("wrong-answer").disabled = true; const name = state.activeClass; let delta = correct ? 2 : -1; if (correct) state.correctAnswers++; else state.correctAnswers = 0; if (state.correctAnswers >= 5) { delta += 2; state.correctAnswers = 0; notify("Série de 5 bonnes réponses : bonus de 2 cases !"); } $("stage-correction").classList.remove("is-hidden"); $("timer-label").textContent = correct ? "Bonne réponse ! Le pion avance…" : "Réponse incorrecte… Le pion recule."; await moveClass(name, delta); renderClasses(); $("next-question").classList.remove("is-hidden"); }
function updateQuestion() { const q = questionSets[state.series][state.question]; $("stage-counter").textContent = `Question ${state.question + 1} / ${questionSets[state.series].length}`; $("stage-question").textContent = q[0]; $("correction-text").textContent = q[2]; const figure = $("question-figure"); figure.src = q[3] || ""; figure.classList.toggle("is-hidden", !q[3]); figure.alt = q[0]; $("timer-value").textContent = q[1]; $("timer-ring").style.setProperty("--progress", "100%"); $("timer-ring").classList.remove("urgent"); $("stage-correction").classList.add("is-hidden"); $("close-correction").classList.add("is-hidden"); $("draw-phase").classList.add("is-hidden"); $("student-phase").classList.add("is-hidden"); $("question-phase").classList.remove("is-hidden"); $("stage-question").classList.remove("is-hidden"); $("correct-answer").classList.add("is-hidden"); $("wrong-answer").classList.add("is-hidden"); $("correct-answer").disabled = false; $("wrong-answer").disabled = false; clearInterval(state.timer); }
function openQuestion() { if (state.moving || state.challengeActive) return; updateQuestion(); $("question-modal").classList.remove("is-hidden"); state.challengeActive = true; startTimer(); }
function startTimer() { clearInterval(state.timer); const seconds = questionSets[state.series][state.question][1]; let left = seconds; $("timer-value").textContent = left; state.timer = setInterval(() => { left--; $("timer-value").textContent = Math.max(0, left); $("timer-ring").style.setProperty("--progress", `${Math.max(0, left / seconds * 100)}%`); if (left <= 10) $("timer-ring").classList.add("urgent"); if (left <= 0) { clearInterval(state.timer); finishQuestionTimer(); } }, 1000); }
function finishQuestionTimer() { $("stage-question").classList.add("is-hidden"); $("question-phase").classList.add("is-hidden"); $("timer-label").textContent = "Le temps est écoulé !"; runStudentDraw(); }
function runStudentDraw() { const name = state.activeClass; const list = students[name] || []; $("draw-phase").classList.remove("is-hidden"); $("student-phase").classList.add("is-hidden"); let count = 0; clearInterval(runStudentDraw.timer); runStudentDraw.timer = setInterval(() => { $("draw-animation-name").textContent = list[Math.floor(Math.random() * list.length)] || "…"; if (++count >= 14) { clearInterval(runStudentDraw.timer); const chosen = list[Math.floor(Math.random() * list.length)] || "Élève"; $("draw-phase").classList.add("is-hidden"); $("student-phase").classList.remove("is-hidden"); $("stage-student-name").textContent = chosen; $("correct-answer").classList.remove("is-hidden"); $("wrong-answer").classList.remove("is-hidden"); } }, 90); }
function drawStudent() { const list = students[state.activeClass] || []; let count = 0; clearInterval(drawStudent.timer); drawStudent.timer = setInterval(() => { $("student-result").textContent = `🎲 ${list[Math.floor(Math.random() * list.length)]}`; if (++count > 12) { clearInterval(drawStudent.timer); const chosen = list[Math.floor(Math.random() * list.length)]; $("student-result").textContent = `🎯 ${chosen}`; notify(`${chosen} est désigné(e) !`); } }, 90); }
function login() { const teacher = teachers[$("teacher-select").value]; if (!teacher || $("password").value !== teacher.password) { notify("Identifiants incorrects"); $("password").value = ""; return; } state.teacher = teacher; state.activeClass = teacher.classes[0]; state.current = 0; $("login-screen").classList.add("is-hidden"); $("class-selection-screen").classList.remove("is-hidden"); $("class-selection-intro").textContent = `${teacher.name}, choisissez la classe avec laquelle vous jouez aujourd’hui.`; $("owned-class-choices").innerHTML = teacher.classes.map((name, index) => `<label class="class-choice ${index === 0 ? "selected" : ""}"><input type="radio" name="active-class" value="${name}" ${index === 0 ? "checked" : ""}> <span>${name}</span></label>`).join(""); }
function enterSelectedClass() { const selected = document.querySelector('input[name="active-class"]:checked'); if (!selected) return; state.activeClass = selected.value; state.current = state.teacher.classes.indexOf(state.activeClass); $("class-selection-screen").classList.add("is-hidden"); $("game-screen").classList.remove("is-hidden"); renderBoard(); updateQuestion(); }
$("login-form").addEventListener("submit", e => { e.preventDefault(); login(); }); $("start-class").addEventListener("click", enterSelectedClass); $("owned-class-choices").addEventListener("change", e => { document.querySelectorAll(".class-choice").forEach(label => label.classList.toggle("selected", label.contains(e.target))); }); $("back-to-login").addEventListener("click", () => { $("class-selection-screen").classList.add("is-hidden"); $("login-screen").classList.remove("is-hidden"); }); $("logout").addEventListener("click", () => { clearInterval(state.timer); state.challengeActive = false; $("game-screen").classList.add("is-hidden"); $("class-selection-screen").classList.add("is-hidden"); $("question-modal").classList.add("is-hidden"); $("login-screen").classList.remove("is-hidden"); }); $("roll-dice").addEventListener("click", openQuestion); $("correct-answer").addEventListener("click", () => applyAnswer(true)); $("wrong-answer").addEventListener("click", () => applyAnswer(false)); $("team-list").addEventListener("click", e => { const button = e.target.closest("button[data-class]"); if (button) moveClass(button.dataset.class, Number(button.dataset.step)); });
